#
###################################
# Site wide configuration
####################################
#
title: daeki's devlog
email: dev.james.jeong@gmail.com
description: To dare is to do.
url: https://daeheejeong.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: daeki's devlog
  avatar: daehee.jpg
  job: Daehee Jeong
  bio: "ì£¼ë‹ˆì–´ ìë°” ë°±ì—”ë“œ ê°œë°œìì…ë‹ˆë‹¤ ğŸ‘¨â€ğŸ’»"
  email: dev.james.jeong@gmail.com
  disqus-shortname: daehee-jeong
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: daeheejeong #username
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  skype: #username
  xing: #username
  instagram: dae_e #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
